name: proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7
  firebase_auth: ^5.6.0
  carousel_slider: ^5.0.0
  http: ^0.13.6
  cached_network_image: ^3.0.0
  youtube_player_flutter: 9.1.1
  url_launcher: ^6.1.10
  image_picker: ^1.1.0
  video_player: ^2.8.2
  chewie: ^1.7.4
  supabase_flutter: ^2.9.1
  flutter_inappwebview: ^6.0.0-beta.24
  firebase_storage: ^12.4.7
 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/imagenes/icono.png" 

flutter:
  uses-material-design: true
  assets:
    - "assets/imagenes/fondo2.png"
