// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU43FBBL_4AoNYFj0r-2wNbQ3yxcwv0xk',
    appId: '1:636360066527:web:5d0f62571a88eb1c08706a',
    messagingSenderId: '636360066527',
    projectId: 'movieapp009',
    authDomain: 'movieapp009.firebaseapp.com',
    databaseURL: 'https://movieapp009-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp009.firebasestorage.app',
    measurementId: 'G-K7Y6VD3WPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATW5qZnuyd6siLa5SVfE6htyzIkC_n3cA',
    appId: '1:636360066527:android:b4a4d26eb31e672208706a',
    messagingSenderId: '636360066527',
    projectId: 'movieapp009',
    databaseURL: 'https://movieapp009-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp009.firebasestorage.app',
  );

}